local Treesitter = {
  TSComment = { fg = C.gray, style = "italic,bold" },
  TSAnnotation = { fg = C.red },
  TSAttribute = { fg = C.cyan },
  TSConstructor = { fg = C.yellow },
  TSType = { fg = C.yellow },
  TSTypeBuiltin = { fg = C.yellow },
  TSConditional = { fg = C.purple },
  TSException = { fg = C.purple },
  TSInclude = { fg = C.blue },
  TSKeyword = { fg = C.purple },
  TSKeywordReturn = { fg = C.red, style = "italic" },
  TSKeywordFunction = { fg = C.purple, style = "italic" },
  TSLabel = { fg = C.blue },
  TSNone = { fg = C.fg },
  TSNamespace = { fg = C.purple },
  TSRepeat = { fg = C.purple },
  TSConstant = { fg = C.orange },
  TSConstBuiltin = { fg = C.orange },
  TSFloat = { fg = C.orange },
  TSNumber = { fg = C.orange },
  TSBoolean = { fg = C.orange },
  TSCharacter = { fg = C.green },
  TSError = { fg = C.error_red },
  TSFunction = { fg = C.blue },
  TSFuncBuiltin = { fg = C.red },
  TSMethod = { fg = C.red },
  TSConstMacro = { fg = C.cyan },
  TSFuncMacro = { fg = C.blue },
  TSProperty = { fg = C.cyan },
  TSOperator = { fg = C.purple },
  TSField = { fg = C.red },
  TSParameter = { fg = C.red },
  TSParameterReference = { fg = C.red },
  TSVariable = { fg = C.fg },
  TSVariableBuiltin = { fg = C.red },
  TSSymbol = { fg = C.cyan },
  TSText = { fg = C.fg },
  TSTextReference = { fg = C.red },
  TSPunctDelimiter = { fg = C.orange },
  TSTagDelimiter = { fg = C.orange },
  TSTagAttribute = { fg = C.orange },
  TSPunctBracket = { fg = C.orange },
  TSPunctSpecial = { fg = C.fg },
  TSString = { fg = C.green },
  TSStringRegex = { fg = C.orange },
  TSStringEscape = { fg = C.orange },
  TSTag = { fg = C.red },
  TSEmphasis = { style = "italic" },
  TSUnderline = { style = "underline" },
  TSNote = { fg = C.info_yellow, style = "bold" },
  TSWarning = { fg = C.warning_orange, style = "bold" },
  TSDanger = { fg = C.error_red, style = "bold" },
  TSTitle = { fg = C.blue, style = "bold" },
  TSLiteral = { fg = C.green },
  TSURI = { fg = C.blue, style = "underline,bold" },
  TSMath = { fg = C.fg },
  TSKeywordOperator = { fg = C.purple },
  TSStructure = { fg = C.fg },
  TSStrong = { fg = C.yellow_orange },
  TSQueryLinterError = { fg = C.warning_orange },
  TSEnvironment = { fg = C.fg },
  TSEnvironmentName = { fg = C.fg },
}

return Treesitter
